from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('CSV/', views.csv_page),
    path('CSV/All/', views.all_csv_download, name='all_csv'),
    path('CSV/Devices/', views.devices_csv),
    path('CSV/Devices/download', views.devices_csv_download, name='devices_csv'),
    path('CSV/LearnACL/', views.learn_acl_csv),
    path('CSV/LearnACL/download', views.learn_acl_csv_download, name='learn_acl_csv'),
    path('CSV/LearnACL/latest', views.learn_acl_csv_download_latest, name='learn_acl_csv_latest'),
    path('CSV/LearnARP/', views.learn_arp_csv),
    path('CSV/LearnARP/download', views.learn_arp_csv_download, name='learn_arp_csv'),
    path('CSV/LearnARP/latest', views.learn_arp_csv_download_latest, name='learn_arp_csv_latest'),
    path('CSV/LearnARPStatistics/', views.learn_arp_statistics_csv),
    path('CSV/LearnARPStatistics/download', views.learn_arp_statistics_csv_download, name='learn_arp_statistics_csv'),
    path('CSV/LearnARPStatistics/latest', views.learn_arp_statistics_csv_download_latest, name='learn_arp_statistics_csv_latest'),
    path('CSV/LearnBGPInstances/', views.learn_bgp_instances_csv),
    path('CSV/LearnBGPInstances/download', views.learn_bgp_instances_csv_download, name='learn_bgp_instances_csv'),
    path('CSV/LearnBGPInstances/latest', views.learn_bgp_instances_csv_download_latest, name='learn_bgp_instances_csv_latest'),
    path('CSV/LearnBGPRoutes/', views.learn_bgp_routes_csv),
    path('CSV/LearnBGPRoutes/download', views.learn_bgp_routes_csv_download, name='learn_bgp_routes_csv'),
    path('CSV/LearnBGPRoutes/latest', views.learn_bgp_routes_csv_download_latest, name='learn_bgp_routes_csv_latest'),
    path('CSV/LearnBGPTables/', views.learn_bgp_tables_csv),
    path('CSV/LearnBGPTables/download', views.learn_bgp_tables_csv_download, name='learn_bgp_tables_csv'),
    path('CSV/LearnBGPTables/latest', views.learn_bgp_tables_csv_download_latest, name='learn_bgp_tables_csv_latest'),
    path('CSV/LearnConfig/', views.learn_config_csv),
    path('CSV/LearnConfig/download', views.learn_config_csv_download, name='learn_config_csv'),
    path('CSV/LearnConfig/latest', views.learn_config_csv_download_latest, name='learn_config_csv_latest'),
    path('CSV/LearnInterface/', views.learn_interface_csv),
    path('CSV/LearnInterface/download', views.learn_interface_csv_download, name='learn_interface_csv'),
    path('CSV/LearnInterface/latest', views.learn_interface_csv_download_latest, name='learn_interface_csv_latest'),
    path('CSV/LearnPlatform/', views.learn_platform_csv),
    path('CSV/LearnPlatform/download', views.learn_platform_csv_download, name='learn_platform_csv'),
    path('CSV/LearnPlatform/latest', views.learn_platform_csv_download_latest, name='learn_platform_csv_latest'),
    path('CSV/LearnPlatformSlots/', views.learn_platform_slots_csv),
    path('CSV/LearnPlatformSlots/download', views.learn_platform_slots_csv_download, name='learn_platform_slots_csv'),
    path('CSV/LearnPlatformSlots/latest', views.learn_platform_slots_csv_download_latest, name='learn_platform_slots_csv_latest'),
    path('CSV/LearnPlatformVirtual/', views.learn_platform_virtual_csv),
    path('CSV/LearnPlatformVirtual/download', views.learn_platform_virtual_csv_download, name='learn_platform_virtual_csv'),
    path('CSV/LearnPlatformVirtual/latest', views.learn_platform_virtual_csv_download_latest, name='learn_platform_virtual_csv_latest'),        
    path('CSV/LearnVLAN/', views.learn_vlan_csv),
    path('CSV/LearnVLAN/download', views.learn_vlan_csv_download, name='learn_vlan_csv'),
    path('CSV/LearnVLAN/latest', views.learn_vlan_csv_download_latest, name='learn_vlan_csv_latest'),
    path('CSV/LearnVRF/', views.learn_vrf_csv),
    path('CSV/LearnVRF/download', views.learn_vrf_csv_download, name='learn_vrf_csv'),
    path('CSV/LearnVRF/latest', views.learn_vrf_csv_download_latest, name='learn_vrf_csv_latest'),
    path('CSV/PSIRT/', views.psirt_csv),
    path('CSV/PSIRT/download', views.psirt_csv_download, name='psirt_csv'),
    path('CSV/PSIRT/latest', views.psirt_csv_download_latest, name='psirt_csv_latest'),
    path('CSV/Recommended/', views.recommended_csv),
    path('CSV/Recommended/download', views.recommended_csv_download, name='recommended_csv'),
    path('CSV/Recommended/latest', views.recommended_csv_download_latest, name='recommended_csv_latest'),
    path('CSV/Serial2Contract/', views.serial2contract_csv),
    path('CSV/Serial2Contract/download', views.serial2contract_csv_download, name='serial2contract_csv'),
    path('CSV/Serial2Contract/latest', views.serial2contract_csv_download_latest, name='serial2contract_csv_latest'),
    path('CSV/ShowInventory/', views.show_inventory_csv),
    path('CSV/ShowInventory/download', views.show_inventory_csv_download, name='show_inventory_csv'),
    path('CSV/ShowInventory/latest', views.show_inventory_csv_download_latest, name='show_inventory_csv_latest'),
    path('CSV/ShowIPInterfaceBrief/', views.show_ip_int_brief_csv),
    path('CSV/ShowIPInterfaceBrief/download', views.show_ip_int_brief_csv_download, name='show_ip_int_brief_csv'),
    path('CSV/ShowIPInterfaceBrief/latest', views.show_ip_int_brief_csv_download_latest, name='show_ip_int_brief_csv_latest'),
    path('CSV/ShowVersion/', views.show_version_csv),
    path('CSV/ShowVersion/download', views.show_version_csv_download, name='show_version_csv'),
    path('CSV/ShowVersion/latest', views.show_version_csv_download_latest, name='show_version_csv_latest'),
]