from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('Netgraph/', views.netgraph_page),
    path('Netgraph/EoX_PID/', views.eox_pid_netgraph),
    path('Netgraph/EoX_PID/JSON/eox_pid_netgraph.json', views.eox_pid_json),
    path('Netgraph/EoX_SN/', views.eox_sn_netgraph),
    path('Netgraph/EoX_SN/JSON/eox_pid_netgraph.json', views.eox_sn_json),
    path('Netgraph/EoX_SW/', views.eox_sw_netgraph),
    path('Netgraph/EoX_SW/JSON/eox_pid_netgraph.json', views.eox_sw_json),
    path('Netgraph/LearnACL/', views.learn_acl_netgraph),
    path('Netgraph/LearnACL/JSON/learned_acl_netgraph.json', views.learn_acl_json),
    path('Netgraph/LearnARP/', views.learn_arp_netgraph),
    path('Netgraph/LearnARP/JSON/learned_arp_netgraph.json', views.learn_arp_json),
    path('Netgraph/LearnARPStatistics/', views.learn_arp_statistics_netgraph),
    path('Netgraph/LearnARPStatistics/JSON/learned_arp_statistics_netgraph.json', views.learn_arp_statistics_json),
    path('Netgraph/LearnBGPInstances/', views.learn_bgp_instances_netgraph),
    path('Netgraph/LearnBGPInstances/JSON/learned_bgp_instances_netgraph.json', views.learn_bgp_instances_json),
    path('Netgraph/LearnInterface/', views.learn_interface_netgraph),
    path('Netgraph/LearnInterface/JSON/learned_interface_netgraph.json', views.learn_interface_json),    
    path('Netgraph/LearnPlatform/', views.learn_platform_netgraph),
    path('Netgraph/LearnPlatform/JSON/learned_platform_netgraph.json', views.learn_platform_json),
    path('Netgraph/LearnVLAN/', views.learn_vlan_netgraph),
    path('Netgraph/LearnVLAN/JSON/learned_vlan_netgraph.json', views.learn_vlan_json),
    path('Netgraph/LearnVRF/', views.learn_vrf_netgraph),
    path('Netgraph/LearnVRF/JSON/learned_vrf_netgraph.json', views.learn_vrf_json),
    path('Netgraph/ShowInventory/', views.show_inventory_netgraph),
    path('Netgraph/ShowInventory/JSON/show_inventory_netgraph.json', views.show_inventory_json),
    path('Netgraph/ShowIPInterfaceBrief/', views.show_ip_interface_brief_netgraph),
    path('Netgraph/ShowIPInterfaceBrief/JSON/show_ip_interface_brief_netgraph.json', views.show_ip_interface_brief_json),
    path('Netgraph/ShowVersion/', views.show_version_netgraph),
    path('Netgraph/ShowVersion/JSON/show_version_netgraph.json', views.show_version_json),    
]