version: '3'
 
services:
  merlin_unchained:
    image: johncapobianco/merlin_unchained:merlin
    build: 
      context: ./
      dockerfile: ./docker/dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - flower
      - merlin_celery_beat00
      - prometheus
  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=merlin
      - POSTGRES_PASSWORD=merlin
      - POSTGRES_DB=merlin
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
  flower:  
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888
    depends_on:
      - redis
      - merlin_celery_beat00
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"     
  merlin_celery_beat00:
    build: 
      context: ./
      dockerfile: ./docker/dockerfile
    command: bash -c "cd /merlin/ && celery -A merlin worker --beat -l INFO"
    restart: on-failure
    volumes:
      - ./merlin/stickydata:/opt/merlin/stickydata
    depends_on:
      - redis
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

volumes:
  prometheus-data:      