# Generated by Django 3.2.6 on 2021-08-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bootflash', models.TextField()),
                ('chassis', models.TextField()),
                ('cpu', models.TextField()),
                ('device_name', models.TextField()),
                ('memory', models.TextField()),
                ('model', models.TextField()),
                ('processor_board_id', models.TextField()),
                ('rp', models.TextField()),
                ('slots', models.TextField()),
                ('days', models.TextField()),
                ('hours', models.TextField()),
                ('minutes', models.TextField()),
                ('seconds', models.TextField()),
                ('name', models.TextField()),
                ('os', models.TextField()),
                ('reason', models.TextField()),
                ('system_compile_time', models.TextField()),
                ('system_image_file', models.TextField()),
                ('system_version', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
