# Generated by Django 3.2.6 on 2021-09-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField()),
                ('alias', models.TextField()),
                ('device_type', models.TextField()),
                ('os', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('protocol', models.TextField()),
                ('ip_address', models.TextField()),
                ('port', models.TextField()),
                ('connection_timeout', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
