# Generated by Django 3.2.6 on 2021-09-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicjobinput',
            name='input_field',
            field=models.JSONField(),
        ),
    ]
