# Generated by Django 3.2.6 on 2021-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0002_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicJobInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_field', models.TextField()),
            ],
        ),
    ]
