# Generated by Django 3.2.7 on 2021-09-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0002_alter_dynamicjobinput_input_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicjobinput',
            name='input_field',
            field=models.TextField(),
        ),
    ]
