# Generated by Django 3.2.6 on 2021-09-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0003_showinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyats_alias', models.TextField()),
                ('os', models.TextField()),
                ('acl', models.TextField()),
                ('ace', models.TextField()),
                ('permission', models.TextField()),
                ('logging', models.TextField()),
                ('source_network', models.TextField()),
                ('destination_network', models.TextField()),
                ('l3_protocol', models.TextField()),
                ('l4_protocol', models.TextField()),
                ('operator', models.TextField()),
                ('port', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
