# Generated by Django 3.2.6 on 2021-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0004_dynamicjobinput_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyats_alias', models.TextField()),
                ('os', models.TextField()),
                ('interface', models.TextField()),
                ('description', models.TextField()),
                ('enabled', models.TextField()),
                ('status', models.TextField()),
                ('access_vlan', models.TextField()),
                ('native_vlan', models.TextField()),
                ('switchport', models.TextField()),
                ('switchport_mode', models.TextField()),
                ('interface_type', models.TextField()),
                ('bandwidth', models.TextField()),
                ('auto_negotiate', models.TextField()),
                ('speed', models.TextField()),
                ('duplex', models.TextField()),
                ('mtu', models.TextField()),
                ('mac_address', models.TextField()),
                ('physical_address', models.TextField()),
                ('ip_address', models.TextField()),
                ('medium', models.TextField()),
                ('delay', models.TextField()),
                ('encapsulation', models.TextField()),
                ('flow_control_receive', models.TextField()),
                ('flow_control_send', models.TextField()),
                ('port_channel', models.TextField()),
                ('port_channel_member', models.TextField()),
                ('last_change', models.TextField()),
                ('input_broadcast', models.TextField()),
                ('input_crc_errors', models.TextField()),
                ('input_errors', models.TextField()),
                ('input_mac_pause_frames', models.TextField()),
                ('input_multicast', models.TextField()),
                ('input_octets', models.TextField()),
                ('input_unicast', models.TextField()),
                ('input_unknown', models.TextField()),
                ('input_total', models.TextField()),
                ('output_broadcast', models.TextField()),
                ('output_discard', models.TextField()),
                ('output_errors', models.TextField()),
                ('output_mac_pause_frames', models.TextField()),
                ('output_multicast', models.TextField()),
                ('output_unicast', models.TextField()),
                ('output_total', models.TextField()),
                ('last_clear', models.TextField()),
                ('input_rate', models.TextField()),
                ('load_interval', models.TextField()),
                ('output_rate', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
