# Generated by Django 3.2.6 on 2021-09-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0005_learnarp_learnarpstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnBGP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyats_alias', models.TextField()),
                ('os', models.TextField()),
                ('instance', models.TextField()),
                ('bgp_id', models.TextField()),
                ('state', models.TextField()),
                ('vrf', models.TextField()),
                ('router_id', models.TextField()),
                ('cluster_id', models.TextField()),
                ('confederation_id', models.TextField()),
                ('neighbor', models.TextField()),
                ('version', models.TextField()),
                ('hold_time', models.TextField()),
                ('keep_alive_interval', models.TextField()),
                ('local_as', models.TextField()),
                ('remote_as', models.TextField()),
                ('total_received', models.TextField()),
                ('total_sent', models.TextField()),
                ('last_reset', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
