# Generated by Django 3.2.6 on 2021-09-20 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0005_learninterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninterface',
            name='port_channel_member_interfaces',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
