# Generated by Django 3.2.6 on 2021-09-15 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0006_learnbgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnbgp',
            name='reset_reason',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
