# Generated by Django 3.2.6 on 2021-09-20 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0006_learninterface_port_channel_member_interfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninterface',
            name='prefix_length',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
