# Generated by Django 3.2.6 on 2021-09-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0008_remove_learninterface_prefix_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyats_alias', models.TextField()),
                ('chassis', models.TextField()),
                ('chassis_sn', models.TextField()),
                ('disk_free_space', models.TextField()),
                ('disk_total_space', models.TextField()),
                ('disk_used_space', models.TextField()),
                ('image', models.TextField()),
                ('installed_packages', models.TextField()),
                ('main_mem', models.TextField()),
                ('os', models.TextField()),
                ('rtr_type', models.TextField()),
                ('slot', models.TextField()),
                ('slot_name', models.TextField()),
                ('slot_sn', models.TextField()),
                ('slot_state', models.TextField()),
                ('slot_redundancy_state', models.TextField()),
                ('rp_boot_image', models.TextField()),
                ('rp_uptime', models.TextField()),
                ('rp_sn', models.TextField()),
                ('version', models.TextField()),
                ('virtual_device', models.TextField()),
                ('virtual_device_type', models.TextField()),
                ('virtual_device_name', models.TextField()),
                ('virtual_device_status', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
