# Generated by Django 3.2.6 on 2021-09-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0009_learnplatform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnplatform',
            name='virtual_device_name',
        ),
    ]
