# Generated by Django 3.2.6 on 2021-09-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0010_remove_learnplatform_virtual_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnplatform',
            name='rp_sn',
        ),
    ]
