# Generated by Django 3.2.6 on 2021-09-21 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0011_remove_learnplatform_rp_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnplatform',
            old_name='virtual_device',
            new_name='virtual_device_member',
        ),
        migrations.RenameField(
            model_name='learnplatform',
            old_name='virtual_device_type',
            new_name='virtual_device_member_status',
        ),
        migrations.AddField(
            model_name='learnplatform',
            name='virtual_device_member_type',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnplatform',
            name='virtual_device_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
