# Generated by Django 3.2.6 on 2021-09-22 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0012_auto_20210921_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnplatform',
            name='slot_rp_uptime',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
