# Generated by Django 3.2.6 on 2021-09-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0013_learnplatform_slot_rp_uptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnPlatformSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.TextField()),
                ('slot_name', models.TextField()),
                ('slot_sn', models.TextField()),
                ('slot_state', models.TextField()),
                ('slot_redundancy_state', models.TextField()),
                ('rp_boot_image', models.TextField()),
                ('slot_rp_uptime', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LearnPlatformVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_device_name', models.TextField()),
                ('virtual_device_status', models.TextField()),
                ('virtual_device_member', models.TextField()),
                ('virtual_device_member_status', models.TextField()),
                ('virtual_device_member_type', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='rp_boot_image',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='slot_name',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='slot_redundancy_state',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='slot_rp_uptime',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='slot_sn',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='slot_state',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='virtual_device_member',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='virtual_device_member_status',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='virtual_device_member_type',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='virtual_device_name',
        ),
        migrations.RemoveField(
            model_name='learnplatform',
            name='virtual_device_status',
        ),
    ]
