# Generated by Django 3.2.6 on 2021-09-22 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0014_auto_20210922_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnplatformslots',
            name='os',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnplatformslots',
            name='pyats_alias',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnplatformvirtual',
            name='os',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnplatformvirtual',
            name='pyats_alias',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
