from django.contrib import admin
from django.urls import path
from . import views
from .views import OnDemandResultAll, OnDemandResultEoPID, OnDemandResultEoSN, OnDemandResultEoSW, OnDemandResultACL, OnDemandResultARP, OnDemandResultBGP, OnDemandResultConfig, OnDemandResultInterface, OnDemandResultPlatform, OnDemandResultVLAN, OnDemandResultVRF, OnDemandResultNMAP, OnDemandResultPSIRT, OnDemandResultRecommended, OnDemandResultSerial2Contract, OnDemandResultInventory, OnDemandResultIPInterfaceBrief, OnDemandResultVersion

urlpatterns = [
    path('OnDemand/', views.button),
    path('OnDemand/GetAll/get_all_all_result/', views.get_all_all_ondemand, name="get_all_all"),
    path('OnDemand/EoPID/eox_pid_all_result/', views.eox_pid_all_ondemand, name="eox_pid_all"),
    path('OnDemand/EoSN/eox_sn_all_result/', views.eox_sn_all_ondemand, name="eox_sn_all"),
    path('OnDemand/EoSW/eox_sw_all_result/', views.eox_sw_all_ondemand, name="eox_sw_all"),
    path('OnDemand/LearnACL/learn_acl_all_result/', views.learn_acl_all_ondemand, name="learn_acl_all"),
    path('OnDemand/LearnARP/learn_arp_all_result/', views.learn_arp_all_ondemand, name="learn_arp_all"),
    path('OnDemand/LearnBGP/learn_bgp_all_result/', views.learn_bgp_all_ondemand, name="learn_bgp_all"),
    path('OnDemand/LearnConfig/learn_config_all_result/', views.learn_config_all_ondemand, name="learn_config_all"),
    path('OnDemand/LearnInterface/learn_interface_all_result/', views.learn_interface_all_ondemand, name="learn_interface_all"),
    path('OnDemand/LearnPlatform/learn_platform_all_result/', views.learn_platform_all_ondemand, name="learn_platform_all"),
    path('OnDemand/LearnVLAN/learn_vlan_all_result/', views.learn_vlan_all_ondemand, name="learn_vlan_all"),
    path('OnDemand/LearnVRF/learn_vrf_all_result/', views.learn_vrf_all_ondemand, name="learn_vrf_all"),
    path('OnDemand/NMAP/nmap_all_result/', views.nmap_all_ondemand, name="nmap_all"),
    path('OnDemand/ShowInventory/show_inventory_all_result/', views.show_inventory_all_ondemand, name="show_inventory_all"),
    path('OnDemand/ShowIPInterfaceBrief/show_ip_int_brief_all_result/', views.show_ip_int_brief_all_ondemand, name="show_ip_int_brief_all"),
    path('OnDemand/ShowVersion/show_version_all_result/', views.show_version_all_ondemand, name="show_version_all"),
    path('OnDemand/PSIRT/psirt_all_result/', views.psirt_all_ondemand, name="psirt_all"),
    path('OnDemand/Recommended/recommended_all_result/', views.recommended_all_ondemand, name="recommended_all"),
    path('OnDemand/Serial2Contract/serial2contract_all_result/', views.serial2contract_all_ondemand, name="serial2contract_all"),
    path('OnDemand/GetAll/get_all_filter_result/', OnDemandResultAll.as_view(), name="get_all_ondemand_filter"),
    path('OnDemand/EoPID/eox_pid_filter_result/', OnDemandResultEoPID.as_view(), name="eox_pid_ondemand_filter"),
    path('OnDemand/EoSN/eox_sn_filter_result/', OnDemandResultEoSN.as_view(), name="eox_sn_ondemand_filter"),
    path('OnDemand/EoSW/eox_sw_filter_result/', OnDemandResultEoSW.as_view(), name="eox_sw_ondemand_filter"),
    path('OnDemand/LearnACL/learn_acl_filter_result/', OnDemandResultACL.as_view(), name="learn_acl_ondemand_filter"),
    path('OnDemand/LearnARP/learn_arp_filter_result/', OnDemandResultARP.as_view(), name="learn_arp_ondemand_filter"),
    path('OnDemand/LearnBGP/learn_bgp_filter_result/', OnDemandResultBGP.as_view(), name="learn_bgp_ondemand_filter"),
    path('OnDemand/LearnConfig/learn_config_filter_result/', OnDemandResultConfig.as_view(), name="learn_config_ondemand_filter"),
    path('OnDemand/LearnInterface/learn_interface_filter_result/', OnDemandResultInterface.as_view(), name="learn_interface_ondemand_filter"),
    path('OnDemand/LearnPlatform/learn_platform_filter_result/', OnDemandResultPlatform.as_view(), name="learn_platform_ondemand_filter"),
    path('OnDemand/LearnVLAN/learn_vlan_filter_result/', OnDemandResultVLAN.as_view(), name="learn_vlan_ondemand_filter"),
    path('OnDemand/LearnVRF/learn_vrf_filter_result/', OnDemandResultVRF.as_view(), name="learn_vrf_ondemand_filter"),
    path('OnDemand/NMAP/nmap_filter_result/', OnDemandResultNMAP.as_view(), name="nmap_ondemand_filter"),
    path('OnDemand/PSIRT/psirt_filter_result/', OnDemandResultPSIRT.as_view(), name="psirt_ondemand_filter"),
    path('OnDemand/Recommended/recommended_filter_result/', OnDemandResultRecommended.as_view(), name="recommended_ondemand_filter"),
    path('OnDemand/Serial2Contract/serial2contract_filter_result/', OnDemandResultSerial2Contract.as_view(), name="serial2contract_ondemand_filter"),
    path('OnDemand/ShowInventory/show_inventory_filter_result/', OnDemandResultInventory.as_view(), name="show_inventory_ondemand_filter"),
    path('OnDemand/ShowIPInterfaceBrief/show_ip_int_brief_filter_result/', OnDemandResultIPInterfaceBrief.as_view(), name="show_ip_int_brief_ondemand_filter"),
    path('OnDemand/ShowVersion/show_version_filter_result/', OnDemandResultVersion.as_view(), name="show_version_ondemand_filter"),
]