FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

ENV DJANGO_SETTINGS_MODULE=merlin.settings
ENV DJANGO_SUPERUSER_EMAIL=admin@automateyournetwork.ca
ENV DJANGO_SUPERUSER_USERNAME=admin
ENV DJANGO_SUPERUSER_PASSWORD=admin

RUN echo "==> Upgrading apk and installing system utilities ...." \
 && apt -y update \
 && apt-get install -y wget \
 && apt-get -y install sudo

RUN echo "==> Installing Python3 and pip ...." \  
 && apt-get install python3 -y \
 && apt install python3-pip -y \
 && apt install openssh-client -y

RUN echo "==> Adding pyATS ..." \
 && pip install pyats[full] \ 
 && pip uninstall --yes markupsafe \
 && pip install markupsafe==1.1.1

RUN echo "==> Adding Django ..." \
 && pip install django

RUN echo "==> Adding Django REST Framework ..." \
 && pip install djangorestframework

RUN echo "==> Adding Celery and Django Celery Beat..." \
 && pip install -U Celery \
 && pip install django-celery-beat

RUN echo "==> Adding Django Prometheus ..." \
 && pip install django-prometheus

RUN echo "==> Adding Django Elasticsarch DSL ..." \
 && pip install django-elasticsearch-dsl

RUN echo "==> Adding Redis (be patient - long step) ..." \
 && wget http://download.redis.io/redis-stable.tar.gz \
 && tar xzf redis-stable.tar.gz \
 && cd redis-stable \
 && sudo make install \
 && pip install redis

RUN echo "==> Adding PostgreSQL ..." \
 && pip install psycopg2-binary

RUN echo "==> Adding Python NMAP ..." \
 && sudo apt-get install nmap -y \
 && pip install python-nmap

RUN echo "==> Adding NPM and Markmap support ..." \
 && sudo DEBIAN_FRONTEND="noninteractive" apt -y install npm \
 && sudo npm install markmap-cli -g

RUN echo "==> Adding Django Google Text to Speech ..." \
 && pip install Django-Gtts

RUN echo "==> Adding Django Phone Number Field..." \
 && pip install django-phonenumber-field[phonenumberslite]

RUN echo "==> Adding Twilio..." \
 && pip install twilio

RUN echo "==> Adding Network JSON Graph..." \
 && npm install netjsongraph.js --save

RUN echo "==> Adding boto3 for S3 Upload..." \
  && pip install boto3

RUN echo "==> Adding Django Storages..." \
  && pip install django-storages

RUN echo "==> Adding Django Channels..." \
  && pip install -U channels

RUN echo "==> Adding Git..." \
  && sudo apt-get -y update \
  && sudo apt install -y git-all

RUN echo "==> Adding Blender Part One Libraries..." \
  && sudo apt -y install build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libglew-dev \
  && sudo apt-get install -y libopenexr-dev

RUN echo "==> Adding Blender Part Two Git Clone..." \
  && mkdir ~/blender-git \
  && cd ~/blender-git \
  && git clone https://git.blender.org/blender.git

RUN echo "==> Adding Blender Part Three x86_64 Library..." \  
  && mkdir ~/blender-git/lib \
  && cd ~/blender-git/lib \
  && svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64

RUN echo "==> Adding Blender Part Four Make..." \
  && sudo apt -y install libomp-dev libomp5 libpng-dev libjpeg9-dev \
  && cd ~/blender-git/blender \
  && make update \
  && make

RUN echo "==> Install Channels Redis..." \
  && pip install channels_redis \
  && cd ~/ 

COPY /images /images/
COPY /merlin /merlin/
COPY /scripts /scripts/

CMD ["/bin/bash", "/scripts/startup.sh"]