FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

ENV DJANGO_SETTINGS_MODULE=merlin.settings
ENV DJANGO_SUPERUSER_EMAIL=admin@automateyournetwork.ca
ENV DJANGO_SUPERUSER_USERNAME=admin
ENV DJANGO_SUPERUSER_PASSWORD=admin

RUN echo "==> Upgrading apk and installing system utilities ...." \
 && apt -y update \
 && apt-get install -y wget \
 && apt-get -y install sudo

RUN echo "==> Installing Python3 and pip ...." \  
 && apt-get install python3 -y \
 && apt install python3-pip -y \
 && apt install openssh-client -y

RUN echo "==> Adding pyATS ..." \
 && pip install pyats[full] \ 
 && pip uninstall --yes markupsafe \
 && pip install markupsafe==1.1.1

RUN echo "==> Adding Django ..." \
 && pip install django

RUN echo "==> Adding Django REST Framework ..." \
 && pip install djangorestframework

RUN echo "==> Adding Celery and Django Celery Beat..." \
 && pip install -U Celery \
 && pip install django-celery-beat

RUN echo "==> Adding Django Prometheus ..." \
 && pip install django-prometheus

RUN echo "==> Adding Django Elasticsarch DSL ..." \
 && pip install django-elasticsearch-dsl

RUN echo "==> Adding Redis (be patient - long step) ..." \
 && wget http://download.redis.io/redis-stable.tar.gz \
 && tar xzf redis-stable.tar.gz \
 && cd redis-stable \
 && sudo make install \
 && pip install redis

RUN echo "==> Adding PostgreSQL ..." \
 && pip install psycopg2-binary

RUN echo "==> Adding Python NMAP ..." \
 && sudo apt-get install nmap -y \
 && pip install python-nmap

RUN echo "==> Adding NPM and Markmap support ..." \
 && sudo DEBIAN_FRONTEND="noninteractive" apt -y install npm \
 && sudo npm install markmap-cli -g

RUN echo "==> Adding Django Google Text to Speech ..." \
 && pip install Django-Gtts

RUN echo "==> Adding Django Phone Number Field..." \
 && pip install django-phonenumber-field[phonenumberslite]

RUN echo "==> Adding Twilio..." \
 && pip install twilio

RUN echo "==> Adding Network JSON Graph..." \
 && npm install netjsongraph.js --save

RUN echo "==> Adding Google Cloud..." \
 && pip install --upgrade gcloud

COPY /images /images/
COPY /merlin /merlin/
COPY /scripts /scripts/

CMD ["/bin/bash", "/scripts/startup.sh"]