from django.contrib import admin

from . import models

admin.site.register(models.Devices)
admin.site.register(models.DynamicJobInput)
admin.site.register(models.EoXCredentials)
admin.site.register(models.EoX_PID)
admin.site.register(models.EoX_SN)
admin.site.register(models.EoX_IOS)
admin.site.register(models.InterfaceEnable)
admin.site.register(models.LearnACL)
admin.site.register(models.LearnARP)
admin.site.register(models.LearnARPStatistics)
admin.site.register(models.LearnBGPInstances)
admin.site.register(models.LearnBGPRoutesPerPeer)
admin.site.register(models.LearnBGPTables)
admin.site.register(models.LearnConfig)
admin.site.register(models.LearnInterface)
admin.site.register(models.LearnPlatform)
admin.site.register(models.LearnPlatformSlots)
admin.site.register(models.LearnPlatformVirtual)
admin.site.register(models.LearnVLAN)
admin.site.register(models.LearnVRF)
admin.site.register(models.NMAP)
admin.site.register(models.RecommendedReleaseCredentials)
admin.site.register(models.RecommendedRelease)
admin.site.register(models.PSIRTCredentials)
admin.site.register(models.PSIRT)
admin.site.register(models.Serial2ContractCredentials)
admin.site.register(models.Serial2Contract)
admin.site.register(models.ShowInventory)
admin.site.register(models.ShowIPIntBrief)
admin.site.register(models.ShowLicenseSummary)
admin.site.register(models.ShowVersion)
admin.site.register(models.TwilioCredentials)
admin.site.register(models.NumbersToCall)
admin.site.register(models.DropBoxCredentials)