"""merlin URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
    path('', include('ondemand.urls')),
    path('Changes/', views.changes),
    path('Changes/all_changes/', views.all_changes, name="all_changes"),
    path('Changes/learn_acl_changes/', views.learn_acl_changes, name="learn_acl_changes"),
    path('Changes/learn_arp_changes/', views.learn_arp_changes, name="learn_arp_changes"),
    path('Changes/learn_arp_statistics_changes/', views.learn_arp_statistics_changes, name="learn_arp_statistics_changes"),
    path('Changes/learn_bgp_instances_changes/', views.learn_bgp_instances_changes, name="learn_bgp_instances_changes"),
    path('Changes/learn_bgp_route_changes/', views.learn_bgp_route_changes, name="learn_bgp_route_changes"),
    path('Changes/learn_bgp_table_changes/', views.learn_bgp_table_changes, name="learn_bgp_table_changes"),
    path('Changes/learn_vlan_changes/', views.learn_vlan_changes, name="learn_vlan_changes"),
    path('Changes/learn_vrf_changes/', views.learn_vrf_changes, name="learn_vrf_changes"),
    path('Changes/show_inventory_changes/', views.show_inventory_changes, name="show_inventory_changes"),
    path('Changes/show_ip_int_brief_changes/', views.show_ip_int_brief_changes, name="show_ip_int_brief_changes"),
    path('Changes/show_version_changes/', views.show_version_changes, name="show_version_changes"),
    path('API/', include('merlin_api.urls')),
    path('Latest/', views.latest),
    path('Latest/All/', views.all_latest),
    path('Latest/LearnACL/', views.learn_acl_latest),
    path('Latest/LearnARP/', views.learn_arp_latest),
    path('Latest/LearnARPStatistics/', views.learn_arp_statistics_latest),
    path('Latest/LearnBGPInstances/', views.learn_bgp_instances_latest),
    path('Latest/LearnBGPRoutes/', views.learn_bgp_routes_latest),
    path('Latest/LearnBGPTables/', views.learn_bgp_tables_latest),
    path('Latest/LearnVLAN/', views.learn_vlan_latest),
    path('Latest/LearnVRF/', views.learn_vrf_latest),
    path('Latest/ShowInventory/', views.show_inventory_latest),
    path('Latest/ShowIPInterfaceBrief/', views.show_ip_int_brief_latest),
    path('Latest/ShowVersion/', views.show_version_latest),
    path('CSV/', views.csv_page),
    path('CSV/download', views.devices_csv_download, name='devices_csv'),
    path('CSV/download', views.learn_acl_csv_download, name='learn_acl_csv'),
    path('CSV/download', views.learn_arp_csv_download, name='learn_arp_csv'),
    path('CSV/download', views.learn_arp_statistics_csv_download, name='learn_arp_statistics_csv'),
    path('CSV/download', views.learn_vlan_csv_download, name='learn_vlan_csv'),
    path('CSV/download', views.learn_vrf_csv_download, name='learn_vrf_csv'),
    path('CSV/download', views.show_inventory_csv_download, name='show_inventory_csv'),
    path('CSV/download', views.show_ip_int_brief_csv_download, name='show_ip_int_brief_csv'),
    path('CSV/download', views.show_version_csv_download, name='show_version_csv'),
    path('CSV/All/', views.all_csv_download, name='all_csv'),
    path('CSV/Devices/', views.devices_csv),
    path('CSV/Devices/download', views.devices_csv_download, name='devices_csv'),
    path('CSV/LearnACL/', views.learn_acl_csv),
    path('CSV/LearnACL/download', views.learn_acl_csv_download, name='learn_acl_csv'),
    path('CSV/LearnACL/latest', views.learn_acl_csv_download_latest, name='learn_acl_csv_latest'),
    path('CSV/LearnARP/', views.learn_arp_csv),
    path('CSV/LearnARP/download', views.learn_arp_csv_download, name='learn_arp_csv'),
    path('CSV/LearnARP/latest', views.learn_arp_csv_download_latest, name='learn_arp_csv_latest'),
    path('CSV/LearnARPStatistics/', views.learn_arp_statistics_csv),
    path('CSV/LearnARPStatistics/download', views.learn_arp_statistics_csv_download, name='learn_arp_statistics_csv'),
    path('CSV/LearnARPStatistics/latest', views.learn_arp_statistics_csv_download_latest, name='learn_arp_statistics_csv_latest'),
    path('CSV/LearnBGPInstances/', views.learn_bgp_instances_csv),
    path('CSV/LearnBGPInstances/download', views.learn_bgp_instances_csv_download, name='learn_bgp_instances_csv'),
    path('CSV/LearnBGPInstances/latest', views.learn_bgp_instances_csv_download_latest, name='learn_bgp_instances_csv_latest'),
    path('CSV/LearnBGPRoutes/', views.learn_bgp_routes_csv),
    path('CSV/LearnBGPRoutes/download', views.learn_bgp_routes_csv_download, name='learn_bgp_routes_csv'),
    path('CSV/LearnBGPRoutes/latest', views.learn_bgp_routes_csv_download_latest, name='learn_bgp_routes_csv_latest'),
    path('CSV/LearnBGPTables/', views.learn_bgp_tables_csv),
    path('CSV/LearnBGPTables/download', views.learn_bgp_tables_csv_download, name='learn_bgp_tables_csv'),
    path('CSV/LearnBGPTables/latest', views.learn_bgp_tables_csv_download_latest, name='learn_bgp_tables_csv_latest'),
    path('CSV/LearnVLAN/', views.learn_vlan_csv),
    path('CSV/LearnVLAN/download', views.learn_vlan_csv_download, name='learn_vlan_csv'),
    path('CSV/LearnVLAN/latest', views.learn_vlan_csv_download_latest, name='learn_vlan_csv_latest'),
    path('CSV/LearnVRF/', views.learn_vrf_csv),
    path('CSV/LearnVRF/download', views.learn_vrf_csv_download, name='learn_vrf_csv'),
    path('CSV/LearnVRF/latest', views.learn_vrf_csv_download_latest, name='learn_vrf_csv_latest'),
    path('CSV/ShowInventory/', views.show_inventory_csv),
    path('CSV/ShowInventory/download', views.show_inventory_csv_download, name='show_inventory_csv'),
    path('CSV/ShowInventory/latest', views.show_inventory_csv_download_latest, name='show_inventory_csv_latest'),
    path('CSV/ShowIPInterfaceBrief/', views.show_ip_int_brief_csv),
    path('CSV/ShowIPInterfaceBrief/download', views.show_ip_int_brief_csv_download, name='show_ip_int_brief_csv'),
    path('CSV/ShowIPInterfaceBrief/latest', views.show_ip_int_brief_csv_download_latest, name='show_ip_int_brief_csv_latest'),
    path('CSV/ShowVersion/', views.show_version_csv),
    path('CSV/ShowVersion/download', views.show_version_csv_download, name='show_version_csv'),
    path('CSV/ShowVersion/latest', views.show_version_csv_download_latest, name='show_version_csv_latest'),
    path('Devices/All/', views.devices_all),
    path('Devices/<int:year>/', views.devices_year_archive),
    path('Devices/<int:year>/<int:month>/', views.devices_month_archive),
    path('Devices/<int:year>/<int:month>/<int:day>/', views.devices_day_archive),
    path('Devices/Hostname/<str:hostname>/', views.devices_hostname_archive),
    path('Devices/Alias/<str:alias>/', views.devices_alias_archive),
    path('Devices/OS/<str:os>', views.devices_os_archive),
    path('Devices/Type/<str:device_type>', views.devices_device_type_archive),
    path('Devices/Username/<str:username>', views.devices_username_archive),
    path('Devices/Protocol/<str:protocol>', views.devices_protocol_archive),
    path('Devices/IP/<str:ip_address>', views.devices_ip_address_archive),
    path('Devices/Port/<str:port>', views.devices_port_archive),
    path('LearnACL/All/', views.learn_acl_all),
    path('LearnACL/<int:year>/', views.learn_acl_year_archive),
    path('LearnACL/<int:year>/<int:month>/', views.learn_acl_month_archive),
    path('LearnACL/<int:year>/<int:month>/<int:day>/', views.learn_acl_day_archive),
    path('LearnACL/nxos/', views.learn_acl_nxos_archive),
    path('LearnACL/<str:pyats_alias>/', views.learn_acl_alias_archive),
    path('LearnARP/All/', views.learn_arp_all),
    path('LearnARP/<int:year>/', views.learn_arp_year_archive),
    path('LearnARP/<int:year>/<int:month>/', views.learn_arp_month_archive),
    path('LearnARP/<int:year>/<int:month>/<int:day>/', views.learn_arp_day_archive),
    path('LearnARP/nxos/', views.learn_arp_nxos_archive),
    path('LearnARP/<str:pyats_alias>/', views.learn_arp_alias_archive),
    path('LearnARPStatistics/All/', views.learn_arp_statistics_all),
    path('LearnARPStatistics/<int:year>/', views.learn_arp_statistics_year_archive),
    path('LearnARPStatistics/<int:year>/<int:month>/', views.learn_arp_statistics_month_archive),
    path('LearnARPStatistics/<int:year>/<int:month>/<int:day>/', views.learn_arp_statistics_day_archive),
    path('LearnARPStatistics/nxos/', views.learn_arp_statistics_nxos_archive),
    path('LearnARPStatistics/<str:pyats_alias>/', views.learn_arp_statistics_alias_archive),
    path('LearnBGPInstances/All/', views.learn_bgp_instances_all),
    path('LearnBGPInstances/<int:year>/', views.learn_bgp_instances_year_archive),
    path('LearnBGPInstances/<int:year>/<int:month>/', views.learn_bgp_instances_month_archive),
    path('LearnBGPInstances/<int:year>/<int:month>/<int:day>/', views.learn_bgp_instances_day_archive),
    path('LearnBGPInstances/nxos/', views.learn_bgp_instances_nxos_archive),
    path('LearnBGPInstances/<str:pyats_alias>/', views.learn_bgp_instances_alias_archive),
    path('LearnBGPRoutes/All/', views.learn_bgp_routes_all),
    path('LearnBGPRoutes/<int:year>/', views.learn_bgp_routes_year_archive),
    path('LearnBGPRoutes/<int:year>/<int:month>/', views.learn_bgp_routes_month_archive),
    path('LearnBGPRoutes/<int:year>/<int:month>/<int:day>/', views.learn_bgp_routes_day_archive),
    path('LearnBGPRoutes/nxos/', views.learn_bgp_routes_nxos_archive),
    path('LearnBGPRoutes/<str:pyats_alias>/', views.learn_bgp_routes_alias_archive),
    path('LearnBGPTables/All/', views.learn_bgp_tables_all),
    path('LearnBGPTables/<int:year>/', views.learn_bgp_tables_year_archive),
    path('LearnBGPTables/<int:year>/<int:month>/', views.learn_bgp_tables_month_archive),
    path('LearnBGPTables/<int:year>/<int:month>/<int:day>/', views.learn_bgp_tables_day_archive),
    path('LearnBGPTables/nxos/', views.learn_bgp_tables_nxos_archive),
    path('LearnBGPTables/<str:pyats_alias>/', views.learn_bgp_tables_alias_archive),        
    path('LearnVLAN/All/', views.learn_vlan_all),
    path('LearnVLAN/<int:year>/', views.learn_vlan_year_archive),
    path('LearnVLAN/<int:year>/<int:month>/', views.learn_vlan_month_archive),
    path('LearnVLAN/<int:year>/<int:month>/<int:day>/', views.learn_vlan_day_archive),
    path('LearnVLAN/nxos/', views.learn_vlan_nxos_archive),
    path('LearnVLAN/<str:pyats_alias>/', views.learn_vlan_alias_archive),
    path('LearnVRF/All/', views.learn_vrf_all),
    path('LearnVRF/<int:year>/', views.learn_vrf_year_archive),
    path('LearnVRF/<int:year>/<int:month>/', views.learn_vrf_month_archive),
    path('LearnVRF/<int:year>/<int:month>/<int:day>/', views.learn_vrf_day_archive),
    path('LearnVRF/nxos/', views.learn_vrf_nxos_archive),
    path('LearnVRF/<str:pyats_alias>/', views.learn_vrf_alias_archive),
    path('ShowInventory/All/', views.show_inventory_all),
    path('ShowInventory/<int:year>/', views.show_inventory_year_archive),
    path('ShowInventory/<int:year>/<int:month>/', views.show_inventory_month_archive),
    path('ShowInventory/<int:year>/<int:month>/<int:day>/', views.show_inventory_day_archive),
    path('ShowInventory/nxos/', views.show_inventory_nxos_archive),
    path('ShowInventory/<str:pyats_alias>/', views.show_inventory_alias_archive),
    path('ShowIPInterfaceBrief/All/', views.show_ip_int_brief_all),
    path('ShowIPInterfaceBrief/<int:year>/', views.show_ip_int_brief_year_archive),
    path('ShowIPInterfaceBrief/<int:year>/<int:month>/', views.show_ip_int_brief_month_archive),
    path('ShowIPInterfaceBrief/<int:year>/<int:month>/<int:day>/', views.show_ip_int_brief_day_archive),
    path('ShowIPInterfaceBrief/nxos/', views.show_ip_int_brief_nxos_archive),
    path('ShowIPInterfaceBrief/<str:pyats_alias>/', views.show_ip_int_brief_alias_archive),    
    path('ShowVersion/All/', views.show_version_all),
    path('ShowVersion/<int:year>/', views.show_version_year_archive),
    path('ShowVersion/<int:year>/<int:month>/', views.show_version_month_archive),
    path('ShowVersion/<int:year>/<int:month>/<int:day>/', views.show_version_day_archive),
    path('ShowVersion/nxos/', views.show_version_nxos_archive),
    path('ShowVersion/<str:pyats_alias>/', views.show_version_alias_archive),
]